name: item-service ci cd

on:
  push:
    branches:
      - main



jobs:
  item:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.4.10
        options: >-
          --name mariadb
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: itemservice
            MYSQL_USER: root
            MYSQL_PASSWORD: ${{ secrets.ROOT_DB_PASSWORD }}
        ports:
          - 3306:3306
    steps:
      - name: GitHub clone
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: application properties 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties

      - name: MariaDB 권한 설정
        run: |
          container_id=$(docker ps -qf "ancestor=mariadb:10.4.10")

      - name: gradle 권한 추가
        run: chmod +x gradlew

      - name: gradle 빌드
        run: ./gradlew clean build